//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace planishor.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string product_name { get; set; }
        public string product_desc { get; set; }
        public System.Web.HttpPostedFile product_image { get; set; }
        public Nullable<System.DateTime> product_created_date { get; set; }
        public Nullable<System.DateTime> product_modified_date { get; set; }
        public Nullable<decimal> product_price { get; set; }
    }
}
